Name: Prasana Shangloo

Roll No: 23102A0076

Class: CMPN - A

R-Programming Week 3

In [ ]:
c(2,3,5,7) + c(-2,-3,-5,8)
# 2+(-2), 3+(-3), 5+(-5), 7+8

[1]  0  0  0 15


In [ ]:
2^3     # Command for power operator
2**3    # Same result

[1] 8
[1] 8


In [ ]:
2^0.5    # square root via power
2**0.5
2^-0.5   # negative power -> reciprocal of root

[1] 1.414214
[1] 1.414214
[1] 0.7071068


In [ ]:
c(2,3,5,7)^2   # 2^2, 3^2, 5^2, 7^2

[1]  4  9 25 49


In [ ]:
c(2,3,5,7)^c(2,3)   # 2^2, 3^3, 5^2, 7^3 -> recycling happens since exponent vector is shorter

[1]   4  27  25 343


In [ ]:
c(1,2,3,4,5,6)^c(2,3,4)   # exponent vector recycled: 1^2,2^3,3^4,4^2,5^3,6^4

[1]    1    8   81   16  125 1296


In [ ]:
c(2,3,5,7)^c(2,3,4)   # length 4 is not a multiple of length 3 -> warning expected

Warning message:
longer object length is not a multiple of shorter object length
[1]   4  27 625  49


In [ ]:
2 %/% 2
5 %/% 2
7 %/% 3

[1] 1
[1] 2
[1] 2


In [ ]:
c(2,3,5,7) %/% 2   # scalar divisor applied to each element

[1] 1 1 2 3


In [ ]:
c(2,3,5,7) %/% c(2,3)   # vector divisor, recycled: 2/%2, 3/%3, 5/%2, 7/%3

[1] 1 1 2 2


In [ ]:
c(2,3,5) %/% c(2,3)   # length 3 not a multiple of length 2 -> warning expected

Warning message:
longer object length is not a multiple of shorter object length
[1] 1 1 2


In [ ]:
2 %% 2
3 %% 2
7 %% 3
7 %% 4

[1] 0
[1] 1
[1] 1
[1] 3


In [ ]:
c(2,3,5,7) %% 2

[1] 0 1 1 1


In [ ]:
c(2,3,5,7) %% c(2,3)   # recycled

[1] 0 0 1 1


In [ ]:
c(2,3,5) %% c(2,3)   # warning: lengths not multiples

Warning message:
longer object length is not a multiple of shorter object length
[1] 0 0 1


In [ ]:
max(1.2, 3.4, -7.8)
max(c(1.2, 3.4, -7.8))   # same result for max

[1] 3.4
[1] 3.4


In [ ]:
min(1.2, 3.4, -7.8)
min(c(1.2, 3.4, -7.8))   # same result for min

[1] -7.8
[1] -7.8


In [ ]:
mean(2, 3, 4)        # NOT what you'd expect: only uses the first argument (2)
mean(c(2, 3, 4))      # correct: (2+3+4)/3 = 3

[1] 2
[1] 3


In [ ]:
abs(-4)
abs(c(-1,-2,-3,4,5))

[1] 4
[1] 1 2 3 4 5


In [ ]:
sqrt(4)
sqrt(c(4,9,16,25))

[1] 2
[1] 2 3 4 5


In [ ]:
sum(c(2,3,5,7))
prod(c(2,3,5,7))

[1] 17
[1] 210


In [ ]:
round(1.23)
round(1.83)

[1] 1
[1] 2


In [ ]:
log(10)        # natural log (ln)
log(exp(1))
log(c(10, 100, 1000))

[1] 2.302585
[1] 1
[1] 2.302585 4.605170 6.907755


In [ ]:
log10(10)      # base-10 log
log10(100)
log10(c(10, 100, 1000))

[1] 1
[1] 2
[1] 1 2 3


In [ ]:
x1 = c(1,2,3,4)
x1

x2 = x1^2
x2

[1] 1 2 3 4
[1]  1  4  9 16


In [ ]:
c(1,2,3,4) + sum(c(1,2,3,4)) * prod(c(1,2))

[1] 21 22 23 24


In [ ]:
abs( c(1,2,3,4) - sum(c(1,2,3,4)) * prod(c(1,2)) )

[1] 19 18 17 16


In [ ]:
x = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))
x

     [,1] [,2]
[1,]    1    5
[2,]    2    6
[3,]    3    7
[4,]    4    8


In [ ]:
x[3,2]

[1] 7


In [ ]:
y = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8), byrow=TRUE)
y

     [,1] [,2]
[1,]    1    2
[2,]    3    4
[3,]    5    6
[4,]    7    8


In [ ]:
dim(x)      # dimensions (rows, cols)
nrow(x)     # number of rows
ncol(x)     # number of columns
mode(x)     # storage mode
attributes(x)   # all attributes, e.g. $dim

[1] 4 2
[1] 4
[1] 2
[1] "numeric"
$dim
[1] 4 2



In [ ]:
# help("matrix")   # uncomment to view documentation
is.matrix(x)
is.matrix(as.matrix(1:10))

[1] TRUE
[1] TRUE


In [ ]:
# 1.
v <- c(4, 9, 16, 25, 36)
sqrt(v)

# 2.
v %/% 5
v %% 5
all((v %/% 5) * 5 + (v %% 5) == v)

# 3.
m <- matrix(1:9, nrow=3, ncol=3, byrow=TRUE)
m
m[2,3]

# 4.
mean(c(10, 20, 30, 40))

Error: non-numeric argument to mathematical function
Error: non-numeric argument to binary operator
Error: non-numeric argument to binary operator
Error: non-numeric argument to binary operator
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9
[1] 6
[1] 25
